-- 1. Create FOLDERS Table
create table public.folders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  user_id uuid references auth.users not null
);

-- 2. Create NOTES Table
create table public.notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  audio_path text, -- Path to file in Storage
  transcript text, -- Full text
  summary text,    -- Bullet points
  quiz jsonb,      -- JSON list of questions
  status text default 'Processing', -- 'Processing', 'Done', 'Error'
  folder_id bigint references public.folders(id), -- Links to a folder (nullable)
  user_id uuid references auth.users not null
);

-- 3. Create STUDY TASKS Table (The one we just fixed!)
create table public.study_tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  due_date text, 
  is_completed boolean default false,
  origin_note_id bigint references public.notes(id) on delete cascade, -- Link to note
  user_id uuid references auth.users not null
);

-- 4. Create FLASHCARDS Table
create table public.flashcards (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  front text not null,
  back text not null,
  note_id bigint references public.notes(id) on delete cascade -- If note is deleted, cards are gone
);

-- 5. Create CHAT MESSAGES Table (For the AI Chat)
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  question text not null,
  response text, -- AI fills this in later
  note_id bigint references public.notes(id) on delete cascade,
  user_id uuid references auth.users not null
);

-- 6. ENABLE REALTIME (So the app updates instantly)
alter publication supabase_realtime add table folders;
alter publication supabase_realtime add table notes;
alter publication supabase_realtime add table study_tasks;
alter publication supabase_realtime add table flashcards;
alter publication supabase_realtime add table chat_messages;

-- 7. ENABLE STORAGE (If you haven't already created the bucket)
-- You usually do this in the Storage UI, but this creates the bucket if missing.
insert into storage.buckets (id, name, public)
values ('Lectures', 'Lectures', true)
on conflict (id) do nothing;